apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-jobmanager-rest
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
  selector:
    app: {{ template "fullname" . }}
    component: jobmanager