apiVersion: v1
kind: Service
metadata:
{{ if .Values.service.name }}
  name: {{ .Values.service.name }}
{{ else }}
  name: {{ template "flink.releaseName" . }}-jobmanager-rest
{{ end }}
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
  selector:
    app: flink-cluster
    release: {{ .Release.Name | quote }}
    component: jobmanager
