apiVersion: v1
kind: Service
metadata:
  name: {{ template "helpers.releaseName" . }}-jobmanager
  labels:
    app: {{ template "helpers.name" . }}
    chart: {{ template "helpers.chartRelease" . }}
    release: {{ .Release.Name | quote }}
    component: jobmanager
spec:
  ports:
    - name: rpc
      port: 6123
    - name: blob
      port: 6124
    - name: query
      port: 6125
    - name: ui
      port: 8081
    - name: ha
      port: 50010
  selector:
    app: flink-cluster
    release: {{ .Release.Name | quote }}
    component: jobmanager