apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-jobmanager
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 6123
    - name: blob
      port: 6124
    - name: ui
      port: 8081
      protocol: TCP
      targetPort: http
  selector:
    app: {{ template "fullname" . }}
    component: jobmanager
